<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Uploads\GroupImages\Group15\51b3efee-611d-43d8-a92a-3725aa37c6ec.png" />
    <Content Include="Uploads\GroupImages\Group15\9b39f323-e508-4796-9ac5-03697f994fa9.png" />
    <Content Include="Uploads\GroupImages\Group15\f0445ccc-a2b9-4edc-b253-761102a5144c.png" />
    <Content Include="Uploads\GroupImages\Group16\50acab67-de46-4a46-b33f-617832cb2460.png" />
    <Content Include="Uploads\GroupImages\Group16\b44c191d-2e79-4895-bc9a-7a0bb781ac21.png" />
    <Content Include="Uploads\GroupImages\Group16\f6cb586e-1277-4201-9017-745f4cc43bb5.png" />
    <Content Include="Uploads\TempIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\ServiceDependencies\" />
  </ItemGroup>

</Project>
